version: 2
updates:
  # Enable version updates for Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    # Specify which dependency updates should trigger security-update PRs
    # when security vulnerabilities are detected 
    security-updates: true
    # Assign the pull requests to specific reviewers
    assignees:
      - "vinayp1277"
    # Labels to apply to pull requests
    labels:
      - "dependencies"
      - "security"
    # Allow up to 3 pull requests for dependencies
    pull-request-branch-name:
      separator: "-"
    # Advanced settings
    commit-message:
      prefix: "dependabot"
      include: "scope"
    # Use GH_TOKEN for authentication
    registries:
      - maven-github
      
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "actions"
    # Use GH_TOKEN for authentication with GitHub actions
    registries:
      - github-actions

# Define GitHub token for authentication
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/*
    username: vinayp1277
    password: ${{secrets.GH_TOKEN}}
  github-actions:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.GH_TOKEN}}
